-- Tessera baseline (V000001).
-- Phase 0 scaffold: the schema starts empty and grows in Phase 1 (Projects & Issues). This anchor
-- establishes the two-dialect migration convention from the first version: the mysql
-- script is the postgresql one with any backslashes doubled.
